### ISSUE TITLE
Getting some failing tests

### ISSUE THREAD

**Issue by dellgreen** [piotrrzysko/simdjson-java#3]
Benchmarks seem to run fine, but seeing some failing tests for some reason, don't know if I'm doing something incorrect?

JUnit test report attached.

Tried using Java 17, 19, 20.

Distro: Ubuntu 22.04.2
kernel: 5.19.0-46-generic
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

[test.tar.gz](https://github.com/piotrrzysko/simdjson-java/files/12094262/test.tar.gz)

**Comment by piotrrzysko** [comment]
Thank you for reporting. I'm aware of that and this is intentional. As the readme says, some features (in this case float parsing) are not implemented yet.
